{% set version = '0.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-osd
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/osd_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/osd/osd_{{ version }}.tar.gz
  sha256: d7742980311db53ee556c976a4a9c5f4a71f97eab3d39838cacdb36c4bb8c9df

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-jade
    - r-nnls
  run:
    - r-base
    - r-jade
    - r-nnls

test:
  commands:
    - $R -e "library('osd')"           # [not win]
    - "\"%R%\" -e \"library('osd')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=osd
  license: GPL-2.0-or-later
  summary: Compound deconvolution for chromatographic data, including gas chromatography - mass
    spectrometry (GC-MS) and comprehensive gas chromatography - mass spectrometry (GCxGC-MS).
    The package includes functions to perform independent component analysis - orthogonal
    signal deconvolution (ICA-OSD), independent component regression (ICR), multivariate
    curve resolution (MCR-ALS) and orthogonal signal deconvolution (OSD) alone.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
